### ISSUE TITLE
pdf automatic download on load?? 

### ISSUE THREAD

**Issue by yvecai** [gravitystorm/blogs.osm.org#20]
That happens on Dolphin and FF on Android,.scary.

**Comment by tomhughes** [comment]
Do you think you could explain the problem you're trying to report in enough details for us to try and reproduce it?

**Comment by yvecai** [comment]
I 'm sorry I can't test on a desktop right now,  but when blogs.openstreetmap.org loads,  my mobile browsers try to download 17-35105-Motion-for-Leave-and-Amicus-Curiae.pdf
Maybe related to post on Mapbox on this subject.

**Comment by tomhughes** [comment]
Well I tried loading blogs.openstreetmap.org in firefox on Android last night and it did no such thing...

**Comment by yvecai** [comment]
It does on FF 50.0.1 & 51.0.2 on my Android 6.0.1
Chrome beta also. 
I don't really know how to check what's going on on mobile.

**Comment by tomhughes** [comment]
I see it in Chromium on Android but not in Firefox.

**Comment by tomhughes** [comment]
Hmm I do see it in Firefox on the desktop, but not in Chrome!

**Comment by tomhughes** [comment]
The mapbox site itself does it if I visit https://www.mapbox.com/blog/mapbox-signs-amicus-brief-opposing-immigration-ban/ in Firefox on the desktop.

**Comment by tomhughes** [comment]
I think it's basically because there's an iframe with the PDF in that blog post and if you don't have a plugin that can render the PDF in place then the browser will present it as a download instead. So my desktop chromium is rendering it in place but as I have pdf.js disabled in my desktop firefox that offers a download.

That article is about to fall off blogs.osm.org anyway...

**Comment by yvecai** [comment]
Ok I'll take the time to warn Mapbox it' s maybe not a so good practice.  
I guess blogs@ is not intended to polish every blog out there.

**Comment by harry-wood** [comment]
Yeah. We could strip out iframes completely but that would cause more breakages than fixes. Basically this is a problem with the source blog content which we don't really need to tackle at the blogs.openstreetmap.org end of things.
