### ISSUE TITLE
maybe add http://dev.overpass-api.de/blog/

### ISSUE THREAD

**Issue by stephan75** [gravitystorm/blogs.osm.org#22]
I am not sure whether the (fresh installed?) blog ov overpass-api.de can be included here?

see http://dev.overpass-api.de/blog/

**Comment by harry-wood** [comment]
Doesn't look like this blog has an atom feed or RSS feed

**Comment by smsm1** [comment]
Agree, there blog is a good contender to be added, however with no atom or RSS feed we are currently unable to add it to the feed aggregator. Please reopen this ticket when there is an atom or RSS feed including a link to the feeds.

**Comment by stephan75** [comment]
According to the referenced issue # 1 a feed is now available.

Can this be included now?
