### ISSUE TITLE
Planet.opml.xml: link for file produces error

### ISSUE THREAD

**Issue by dorotheakazazi** [gravitystorm/blogs.osm.org#26]
Hello,

[The link for the file "OPML feed of all feeds"](https://blogs.openstreetmap.org/planet.opml.xml), which is located on the bottom of the list on the right side of the page https://blogs.openstreetmap.org/ , when clicked it currently opens a "Not Found" page:

_Not Found
The requested URL /planet.opml.xml was not found on this server.
Apache/2.4.7 (Ubuntu) Server at blogs.openstreetmap.org Port 443_

Tested on several days in March. Thanks for having a look :)

**Comment by geraldb** [comment]
@dorotheakazazi  FYI: Use <https://blogs.openstreetmap.org/opml.xml>  instead of planet.opml.xml than it works. The link in the [blank.html.erb](https://github.com/gravitystorm/blogs.osm.org/blob/master/theme/blank.html.erb#L53) template is wrong. Cheers.

**Comment by harry-wood** [comment]
Yeah I was noticing the correct URL looks like it should be https://blogs.openstreetmap.org/opml.xml because something's happening there, but... error

**Comment by geraldb** [comment]
I checked the opml.xml - it's present (that is, it gets generated from the template) - it's just a xml encoding error in line 25 e.g.:
    
     text=""Geofabrik: Notizen aus der Maschinenhalle""

that is, the quotes inside quotes need to get escaped, otherwise the xml gets messed up e.g.

    text="&quot;Geofabrik: Notizen aus der Maschinenhalle&quot;"

**Comment by dorotheakazazi** [comment]
Thanks @geraldb and @harry-wood :)
