### ISSUE TITLE
Add klokantech blog

### ISSUE THREAD

**Issue by smsm1** [gravitystorm/blogs.osm.org#32]
I've had the following message to add the klokantech blog:

Hi smsm1,

I am writing you due to request to add our blog into blogs summary at blogs.osm.org.

Our blog is located at https://blog.klokantech.com/, the entries with OpenStreetMap tag are here https://blog.klokantech.com/tags/#openstreetmap , the feed filtered by OpenStreetMap tag is located here https://blog.klokantech.com/feed/openstreetmap.xml .

Thank you.

Best regards, Jiří Komárek

**Comment by klokan** [comment]
Our OpenStreetMap tagged blog posts are mostly about the open-source OpenMapTiles.org project...

Now we plan to announce the upcoming new release - bringing Wikidata/Wikipedia binding with OpenStreetMap features into the open source vector tiles. It means more translations of place names in maps like https://openmaptiles.org/languages/de/.

Other messages are similar...

It would be great if you can add it, Andy (@gravitystorm), thanks!
