### ISSUE TITLE
Updates have stopped

### ISSUE THREAD

**Issue by systemed** [gravitystorm/blogs.osm.org#34]
https://blogs.openstreetmap.org/ hasn't updated since Sunday. Not sure whether this is a blogs.osm.org issue or an ops one, but figured it couldn't hurt to post here.

**Comment by tomhughes** [comment]
Neither really - ti's a combination of @smsm1's blog being down and pluto not handling that well and giving up on the whole thing because one URL times out.

**Comment by smsm1** [comment]
My blog was down for a bit on Sunday while doing a server upgrade. Seems to be fine now with the redirect to Feedburner which has been there for years.

If it is still an issue happy for my blog to be removed as don't foresee me writing many osm related posts in the near future.

**Comment by tomhughes** [comment]
@smsm1 it looks like IPv4 is working but IPv6 isn't.

**Comment by smsm1** [comment]
Good spot, I'll try and take a look.

**Comment by smsm1** [comment]
As an interim measure I've removed the IPv6 DNS record.

**Comment by tomhughes** [comment]
Updates are working again now.

**Comment by smsm1** [comment]
It's updating again now that I've removed the IPv6 DNS records.

**Comment by systemed** [comment]
It's died again: no updates since Monday.

**Comment by tomhughes** [comment]
Sure, but I really have better things to do in life then constantly disabling feed when they break and then getting shouted at by those same people for having had the temerity to prevent them publishing their broken shit to the world.

**Comment by tomhughes** [comment]
For the record `tom_chance` appears to be the current HTTP 500 compliant culprit.

**Comment by systemed** [comment]
Oh I know, I'm just logging a data point here in the hope that maybe Pluto will become less of a fragile flower or something.

**Comment by systemed** [comment]
So pinging @tomchance, I guess...

**Comment by tomhughes** [comment]
It actually looks like it is working now but it definitely was complaining earlier.

**Comment by tomchance** [comment]
Erk. If my blog is creating a problem please do just remove it from the list. I've not blogged about OSM for some years.

**Comment by systemed** [comment]
Stopped again.

**Comment by tomhughes** [comment]
Yes, because weeklyosm is down, but I'd probably get quite a lot of shit if I removed that.
