### ISSUE TITLE
osm.be dates

### ISSUE THREAD

**Issue by systemed** [gravitystorm/blogs.osm.org#38]
Currently the OpenStreetMap Belgium feed appears to be supplying dates of upcoming events in the feed.

This means that the top entry on blogs.osm.org is currently a February osm.be meeting and will presumably stay as such until nearer the time.

Not sure whether this is an osm.be feed issue or a blogs.osm.org parsing issue.

**Comment by tomhughes** [comment]
An osm.be issue I assume, or rather it's a poor interaction with neither side really at fault.

**Comment by systemed** [comment]
It appears to be an issue with their feed, which contains the contradictory:

    <updated>2019-01-03T10:40:21+00:00</updated>
    <published>2019-02-04T00:00:00+00:00</published>

I'll do a PR to remove the feed.
