### ISSUE TITLE
Add Mapillary blog?

### ISSUE THREAD

**Issue by harry-wood** [gravitystorm/blogs.osm.org#43]
@RobJN suggested adding Mapillary's blog

https://blog.mapillary.com/

Looks good to me. It seems very on-topic without any need for filtering or category.

Do they _want_ it to be added? [I'll ask them](https://twitter.com/harry_wood/status/1187911561773498368)

**Comment by RobJN** [comment]
Unless a long time ago, I don't think it was my suggestion. I'd be fine with it though :-)
