### ISSUE TITLE
XML parse error in ATOM and RSS feed if link contains special characters.

### ISSUE THREAD

**Issue by jfg956** [gravitystorm/blogs.osm.org#52]
Hi,

If the link to a blog contains a special character, there will be XML parse error in the generated ATOM and RSS feeds.

In rss.xml.erb we have below:

```
  <guid><%= item.guid %></guid>
  <link><%= item.url %></link>
```

It is fixed by replacing by this:

```
  <guid><%= CGI.escapeHTML(item.guid) %></guid>
  <link><%= CGI.escapeHTML(item.url) %></link>
```

And in atom.xml.erb we have below for which a similar fix as above is needed.

```
    <link href="<%= item.url %>"/>
    <id><%= item.guid %></id>
```

Cheers, Jean-François Gagné

**Comment by jfg956** [comment]
Link to pull request fixing this:
[Fix bug "XML parse error in ATOM and RSS feed if link contains special characters". ](https://github.com/gravitystorm/blogs.osm.org/pull/53)

**Comment by harry-wood** [comment]
I think we can close this one. Fixed by the merged PR ^ right?

**Comment by jfg956** [comment]
Yes, this should have been closed, thanks for the cleanup.
