### ISSUE TITLE
New Blog - overflorian

### ISSUE THREAD

**Issue by overflorian** [gravitystorm/blogs.osm.org#56]
Hi,
I'm a french contributor known under the nickname of overflorian (https://www.openstreetmap.org/user/overflorian)
I sometimes post over my blog http://florian.lainez.fr only about OSM in french and english.

Could you please add to the list the feed http://florian.lainez.fr/feed ?
Thanks

**Comment by harry-wood** [comment]
Sorry for the delay Florian. Your blog is added: https://github.com/gravitystorm/blogs.osm.org/commit/7e8751ea5e62a2caf26684356c3f2d2accd54335

**Comment by overflorian** [comment]
Thanks
