### ISSUE TITLE
New OSM blog: andreas.scherbaum.la

### ISSUE THREAD

**Issue by andreasscherbaum** [gravitystorm/blogs.osm.org#58]
Hi there,

I would like to add the OpenStreetMap related content of my blog to the aggregator.
* My blog: https://andreas.scherbaum.la/blog/
* OSM content RSS feed: https://andreas.scherbaum.la/blog/feeds/categories/77-OpenStreetMap.rss
* Blog name: ads' corner
* OSM profile: https://www.openstreetmap.org/user/a_d_s

Thanks,
Andreas

**Comment by harry-wood** [comment]
Sorry. We were a bit slow on the uptake there. Will you be doing any more OpenStreetMap related blog posts @andreasscherbaum ? If so, this RSS feed looks good to me.

**Comment by andreasscherbaum** [comment]
Hi @harry-wood I indeed plan to post occasionally. Thanks.

**Comment by harry-wood** [comment]
Cool. That's added: https://github.com/gravitystorm/blogs.osm.org/commit/4510608659ede1f449bf19f58ef5fed43632a5cc  Looking forward to seeing more OpenStreetMap posts from you!
