### ISSUE TITLE
Limit image size

### ISSUE THREAD

**Issue by smsm1** [gravitystorm/blogs.osm.org#8]
There's been a couple of requests to prevent the overspill of the images by using CSS such as:

```
img {
    max-width: 100%;
}
```

Need to check if this is still an issue, it's possible it's already been catered for.

**Comment by harry-wood** [comment]
No. Still an issue e.g. at the current time this a massive planet earth image coming in from this blog post: https://www.mapbox.com/blog/goes-16/ making the whole site get a 1600pixel wide scrollbar

(BTW  I made a issue for this in your upstream repo: https://github.com/smsm1/blogs.osm.org/issues/8 ? Should we move issues over and close down the issue tracker there? )

**Comment by yvecai** [comment]
Images are now pushed down under the right feed list,  leaving a long blank on the first post.
